import { getStaffUser } from '@/app/auth';
import { cookies } from 'next/headers';
import { database,one,all,run,id,now,hash,parse,clean,fail,rate,log,configDefault,safeurl,clientIp } from '@/lib/desk';
export const dynamic='force-dynamic';
const INVITE_MS=7*86400000;
// One-time staff login code, e.g. K7PQ2-XM4TD. Unambiguous characters; 32 symbols keeps the byte modulo unbiased.
function loginCode(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c=Array.from(crypto.getRandomValues(new Uint8Array(10)),x=>a[x%32]).join('');return c.slice(0,5)+'-'+c.slice(5);}
async function membership(h:string){const u=await getStaffUser();if(!u)fail('Sign in to your staff account.',401);let m=await one('SELECT * FROM members WHERE hotel=? AND email=? AND active=1',h,u.email.toLowerCase());if(!m||(m.user&&m.user!==u.userId))fail('You do not have access to this hotel.',403);if(!m.user)await run('UPDATE members SET user=? WHERE id=? AND user IS NULL',u.userId,m.id);return m;}
const head=(m:any)=>{if(!['admin','head'].includes(m.role))fail('Only a hotel or department head can do this.',403);};
const admin=(m:any)=>{if(m.role!=='admin')fail('Only a hotel administrator can do this.',403);};
async function guest(qr:string){const room=await one('SELECT * FROM rooms WHERE qr=? AND active=1',qr);if(!room)fail('This QR code is unavailable.',404);const ck=(await cookies()).get('guest_'+room.id)?.value;let ss=ck?await one('SELECT * FROM guest_sessions WHERE id=? AND room=? AND expires>?',await hash(ck),room.id,now()):null;let stay=ss?.stay?await one('SELECT * FROM stays WHERE id=? AND room=? AND active=1 AND checkin<=? AND checkout>?',ss.stay,room.id,now(),now()):null;if(room.kind==='room'&&!stay)ss=null;return {room,ss,stay};}
async function guestSession(room:any,stay:any){let token=id()+id(), expires=stay?Math.min(stay.checkout,now()+86400000*14):now()+86400000*7;let sid=await hash(token);await run('INSERT INTO guest_sessions VALUES (?,?,?,?)',sid,room.id,stay?.id||null,expires);(await cookies()).set('guest_'+room.id,token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:Math.floor((expires-now())/1000)});return sid;}
function visible(r:any,m:any){if(m.role==='staff')return r.assignee===m.id;if(m.role==='head')return r.department===m.department;return true;}
async function requestAccess(b:any){if(b.qr){let g=await guest(b.qr);if(!g.ss)fail('Please unlock your room first.',401);let r=await one('SELECT * FROM requests WHERE id=? AND hotel=?',b.id,g.room.hotel);if(!r||!(g.stay?r.stay===g.stay.id:r.session===g.ss.id))fail('Request not found.',404);return {r,g,m:null};}let m=await membership(b.hotel);let r=await one('SELECT * FROM requests WHERE id=? AND hotel=?',b.id,b.hotel);if(!r||!visible(r,m))fail('Request not found.',404);return {r,m,g:null};}
export async function GET(req:Request){try{const p=new URL(req.url).searchParams;let action=p.get('action');if(action==='guest'){const g=await guest(p.get('qr')||'');let hotel=await one('SELECT id,name,config FROM hotels WHERE id=?',g.room.hotel);let sv=await all("SELECT * FROM services WHERE hotel=? AND status='published'",g.room.hotel);sv=g.room.kind==='room'?sv:[];return Response.json({hotel:{...hotel,config:parse(hotel.config)},room:{id:g.room.id,label:g.room.label,kind:g.room.kind},unlocked:!!g.ss,stay:g.stay?{name:g.stay.name,checkout:g.stay.checkout}:null,services:sv.map(s=>({...s,config:parse(s.config)})),places:(await all('SELECT * FROM places WHERE hotel=? AND active=1',g.room.hotel)).map(s=>({...s,config:parse(s.config)})),charges:g.stay?await all('SELECT * FROM charges WHERE stay=? ORDER BY created',g.stay.id):[],requests:g.ss?await all(g.stay?'SELECT * FROM requests WHERE stay=? ORDER BY created DESC':'SELECT * FROM requests WHERE session=? ORDER BY created DESC',g.stay?.id||g.ss.id):[]});}
if(action==='events'){let a=await requestAccess({id:p.get('id'),hotel:p.get('hotel'),qr:p.get('qr')});return Response.json(await all(a.g?"SELECT * FROM events WHERE request=? AND kind!='internal' ORDER BY created":"SELECT * FROM events WHERE request=? ORDER BY created",a.r.id));}
const user=await getStaffUser();if(!user)return Response.json({user:null,hotels:[]});let hotels=await all('SELECT h.id,h.name,m.role FROM hotels h JOIN members m ON m.hotel=h.id WHERE m.email=? AND m.active=1 AND (m.user IS NULL OR m.user=?) ORDER BY h.created',user.email.toLowerCase(),user.userId);let h=p.get('hotel');if(!h)return Response.json({user,hotels});let m=await membership(h);let hotel=await one('SELECT * FROM hotels WHERE id=?',h);let rr=await all('SELECT * FROM requests WHERE hotel=? ORDER BY created DESC',h);rr=rr.filter(r=>visible(r,m));return Response.json({user,hotels,member:m,hotel:{...hotel,config:parse(hotel.config)},requests:rr,services:(await all('SELECT * FROM services WHERE hotel=?',h)).map(s=>({...s,config:parse(s.config)})),places:(await all('SELECT * FROM places WHERE hotel=?',h)).map(s=>({...s,config:parse(s.config)})),members:await all('SELECT id,name,email,role,department,active,user IS NOT NULL AS joined FROM members WHERE hotel=?',h),rooms:m.role==='admin'?await all('SELECT r.*,v.count as scans FROM rooms r LEFT JOIN visits v ON r.id=v.room WHERE hotel=? ORDER BY label',h):[],charges:m.role==='admin'?await all('SELECT * FROM charges WHERE hotel=? ORDER BY created',h):[],stays:m.role==='admin'?await all('SELECT id,room,name,checkin,checkout,active FROM stays WHERE hotel=? ORDER BY checkin DESC',h):[]});}catch(e:any){console.error('desk',e.message);return Response.json({error:e.status?e.message:'Could not load data. Please retry.'},{status:e.status||503});}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)fail('Invalid request origin.',403);const b:any=await req.json();const action=b.action;const t=now();
if(action==='visit'){let g=await guest(b.qr);await run('INSERT INTO visits VALUES (?,1,?) ON CONFLICT(room) DO UPDATE SET count=count+1,last=excluded.last',g.room.id,t);return Response.json({ok:true});}
if(action==='unlock'){let g=await guest(b.qr);if(g.room.kind!=='room')fail('This QR is for information only.',403);await rate('pin:'+g.room.id+':'+clientIp(req),8);await rate('pinroom:'+g.room.id,40);let stay=await one('SELECT * FROM stays WHERE room=? AND active=1 AND checkin<=? AND checkout>?',g.room.id,t,t);if(!stay||await hash(stay.id+clean(b.pin))!==stay.pin)fail('Incorrect or expired room access code.',401);await guestSession(g.room,stay);return Response.json({ok:true});}
if(action==='submit'){let g=await guest(b.qr);if(g.room.kind!=='room')fail('Common-area QR pages are browse-only.',403);if(g.room.kind==='room'&&!g.ss)fail('Unlock your room to place a request.',401);if(!g.ss){let sid=await guestSession(g.room,null);g.ss={id:sid};}await rate('submit:'+g.ss.id,40);let retry=clean(b.retry,80);if(!retry)fail('Request reference missing. Please retry.');let existing=await one('SELECT id FROM requests WHERE session=? AND retry=?',g.ss.id,retry);if(existing)return Response.json({id:existing.id});let arr=Array.isArray(b.items)?b.items:[];if(!arr.length||arr.length>20)fail('Select a service.');let hotel=await one('SELECT config FROM hotels WHERE id=?',g.room.hotel),hc=parse(hotel.config);let snapshots:any[]=[],total=0,quote=false,dept='',category='',mins=30;
for(let item of arr){let s=await one("SELECT * FROM services WHERE id=? AND hotel=? AND status='published'",item.id,g.room.hotel);if(!s||(g.room.kind==='public'&&s.audience!=='public'))fail('This service is not available.');let c=parse(s.config);if(c.available===false)fail(s.name+' is temporarily unavailable.');let qty=Number(item.qty);if(!Number.isInteger(qty)||qty<1||qty>Math.min(Number(c.maxQty)||20,100))fail('Check item quantities.');if(dept&&dept!==s.department)fail('Place requests for different departments separately.');dept=s.department;category=s.category;mins=Number(c.minutes)||30;let variant=(c.variants||[]).find((v:any)=>v.name===item.variant);if((c.variants||[]).length&&!variant)fail('Select an option for '+s.name);let price=c.mode==='Free'?0:Number(variant?.price??c.price??0);if(!Number.isFinite(price)||price<0)fail('Service price needs updating.');if(c.mode==='Quote required')quote=true;
if(c.open&&c.close&&c.open!==c.close){let serviceTime=b.details?.when?new Date(b.details.when).getTime():t;if(!Number.isFinite(serviceTime))fail('Choose a valid service time.');let hr=new Intl.DateTimeFormat('en-GB',{timeZone:hc.timezone||'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}).format(serviceTime);let available=c.open<c.close?hr>=c.open&&hr<c.close:hr>=c.open||hr<c.close;if(!available)fail(s.name+' is outside operating hours. Choose a scheduled time.');}
const tax=Math.round(price*qty*(Number(c.tax)||0)/100),fee=Math.round(Number(c.fee)||0);let subtotal=price*qty+tax+fee;total+=subtotal;snapshots.push({id:s.id,name:s.name,variant:variant?.name||'',qty,price,tax,fee,subtotal,mode:c.mode});}
if(b.details?.when){let dt=new Date(b.details.when).getTime();if(!Number.isFinite(dt)||dt<t-60000)fail('Choose a future date and time.');}let name=g.stay?.name||clean(b.name,100),contact=clean(b.contact,150);if(!name||(!g.stay&&!contact))fail('Enter your name and contact for the booking.');let rid=id();let detail={note:clean(b.details?.note,1500),when:clean(b.details?.when),destination:clean(b.details?.destination),people:clean(b.details?.people,20),language:clean(b.details?.language,60)};let out=await run('INSERT INTO requests VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',rid,g.room.hotel,g.room.id,g.stay?.id||null,g.ss.id,g.room.label,name,contact,snapshots.map(s=>s.name+(s.qty>1?' × '+s.qty:'')).join(', '),category,dept,JSON.stringify(snapshots),JSON.stringify(detail),quote?null:total,'New',null,t,t,t+mins*60000,1,retry);await log(g.room.hotel,rid,name,'status','Request received. Awaiting staff confirmation.');return Response.json({id:rid});}
if(['message','transition','assign','quote'].includes(action)){let {r,m,g}=await requestAccess(b);let actor=m?.name||g?.stay?.name||r.name;
if(action==='message'){let body=clean(b.body,2000);if(!body)fail('Write a message.');await log(r.hotel,r.id,actor,b.internal&&m?'internal':'message',body);return Response.json({ok:true});}
let status=r.status,assignee=r.assignee,total=r.total,details=parse(r.details),due=r.due;
if(action==='assign'){if(!m)fail('Not authorised.',403);head(m);let a=await one('SELECT * FROM members WHERE id=? AND hotel=? AND active=1',b.assignee,r.hotel);if(!a||a.department!==r.department&&a.role!=='admin')fail('Select an active employee in this department.');if(['Completed','Cancelled','Rejected'].includes(r.status))fail('Reopen this task before assigning.');if(r.assignee&&r.assignee!==a.id&&!clean(b.reason))fail('Enter a reassignment reason.');assignee=a.id;status=['New','Blocked'].includes(status)?'Assigned':status;due=b.due?new Date(b.due).getTime():r.due;if(!Number.isFinite(due))fail('Invalid deadline.');details.priority=['Normal','High','Urgent'].includes(b.priority)?b.priority:details.priority||'Normal';}
if(action==='quote'){if(!m)fail('Not authorised.',403);head(m);if(await one('SELECT id FROM charges WHERE request=? AND voided=0',r.id))fail('This item is already on the room bill. Cancel it with a reason before submitting a replacement.');if(['Completed','Cancelled','Rejected'].includes(status))fail('This request is closed.');total=Math.round(Number(b.total)*100);if(!Number.isFinite(total)||total<0)fail('Enter a valid total.');if(!clean(b.reason))fail('Add quote inclusions and terms.');status='Awaiting approval';details.quote=clean(b.reason,1500);}
if(action==='transition'){let target=clean(b.status);if(g){if(target==='Approved'&&status==='Awaiting approval')status=target;else if(target==='Cancelled'&&['New','Assigned','Acknowledged','Awaiting approval','Approved'].includes(status))status=target;else fail('This action is not available. Contact reception.');}else{if(!m)fail('Not authorised.',403);if(m.role==='staff'&&r.assignee!==m.id)fail('This task is not assigned to you.',403);const options:Record<string,string[]>={'New':['Rejected','Cancelled'],'Assigned':['Acknowledged','Blocked'],'Acknowledged':['In progress','Blocked','Cancelled'],'In progress':['Done','Blocked','Cancelled'],'Blocked':['In progress'],'Done':['Completed','In progress','Cancelled'],'Awaiting approval':['Cancelled'],'Approved':['Confirmed','Cancelled'],'Confirmed':['In progress','Blocked','Cancelled'],'Rejected':['New'],'Cancelled':['New'],'Completed':['New','Cancelled']};if(!(options[status]||[]).includes(target))fail('Invalid status change. Refresh the request.');if(['Completed','New','Rejected','Cancelled','Confirmed'].includes(target))head(m);if(['Blocked','Rejected','Cancelled','New'].includes(target)&&!clean(b.reason))fail('Please enter a reason.');if(target==='Confirmed'&&!clean(b.reason))fail('Record availability or supplier confirmation.');status=target;}}
if(['Acknowledged','In progress','Done','Confirmed','Completed'].includes(status)&&total===null)fail('Send a quote and obtain guest approval before proceeding.');
if(status==='Confirmed'&&!assignee)fail('Assign a coordinator before confirming.');
if(status==='New'&&await one('SELECT id FROM charges WHERE request=?',r.id))fail('Create a new request for this previously billed service.');
const ver=Number(b.version);if(ver!==r.version)fail('This request changed. Refresh and try again.',409);
const ops=[database().prepare('UPDATE requests SET status=?,assignee=?,total=?,details=?,due=?,version=version+1,updated=? WHERE id=? AND version=?').bind(status,assignee,total,JSON.stringify(details),due,t,r.id,ver)];
if(r.stay&&total!==null&&total>0&&['Acknowledged','In progress','Done','Confirmed','Completed'].includes(status))ops.push(database().prepare('INSERT OR IGNORE INTO charges SELECT ?,hotel,stay,id,title,total,0,? FROM requests WHERE id=? AND version=? AND status=?').bind(id(),t,r.id,ver+1,status));
if(['Cancelled','Rejected'].includes(status))ops.push(database().prepare('UPDATE charges SET voided=1 WHERE request=? AND EXISTS (SELECT 1 FROM requests WHERE id=? AND version=? AND status=?)').bind(r.id,r.id,ver+1,status));
let result=await database().batch(ops);if(!result[0].meta.changes)fail('This request changed. Refresh and try again.',409);
await log(r.hotel,r.id,actor,'status',action==='assign'?`Assigned to ${(await one('SELECT name FROM members WHERE id=?',assignee)).name}. ${clean(b.reason)}`:action==='quote'?`Quote sent: ${total/100}. ${clean(b.reason)}`:`${status}${b.reason?': '+clean(b.reason):''}`);return Response.json({ok:true});}
const user=await getStaffUser();if(!user)fail('Sign in to continue.',401);
if(action==='createHotel'){let name=clean(b.name,100);if(!name)fail('Enter a hotel name.');if(!await one('SELECT 1 AS x FROM hotels WHERE owner=?',user.userId)&&await one('SELECT 1 AS x FROM members WHERE email=?',user.email.toLowerCase()))fail('Staff accounts cannot create hotels. Ask the hotel owner.',403);await rate('hotels:'+user.userId,10);let h=id();await database().batch([database().prepare('INSERT INTO hotels VALUES (?,?,?,?,?)').bind(h,name,user.userId,JSON.stringify(configDefault),t),database().prepare('INSERT INTO members (id,hotel,email,user,name,role,department,active) VALUES (?,?,?,?,?,?,?,?)').bind(id(),h,user.email.toLowerCase(),user.userId,user.displayName,'admin','Reception',1)]);return Response.json({id:h});}
let m=await membership(b.hotel);admin(m);let extra:any={};
if(action==='settings'){let current=await one('SELECT * FROM hotels WHERE id=?',b.hotel);let cfg:any={...configDefault,...parse(current.config)};for(let k of Object.keys(configDefault))if(b.config?.[k]!==undefined)cfg[k]=clean(b.config[k],k==='policies'?4000:1000);try{new Intl.DateTimeFormat('en',{timeZone:cfg.timezone});new Intl.NumberFormat('en',{style:'currency',currency:cfg.currency})}catch{fail('Check timezone and currency.');}cfg.image=safeurl(cfg.image);await run('UPDATE hotels SET name=?,config=? WHERE id=?',clean(b.name,100)||current.name,JSON.stringify(cfg),b.hotel);}
else if(action==='room'){if(!clean(b.label))fail('Enter a room or location name.');if(b.id){let old=await one('SELECT * FROM rooms WHERE id=? AND hotel=?',b.id,b.hotel);if(!old)fail('Room not found.');await run('UPDATE rooms SET label=?,active=? WHERE id=?',clean(b.label,100),b.active===false?0:1,b.id);}else{if(await one('SELECT id FROM rooms WHERE hotel=? AND label=?',b.hotel,clean(b.label,100)))fail('That room or location already exists.');await run('INSERT INTO rooms VALUES (?,?,?,?,?,?)',id(),b.hotel,clean(b.label,100),b.kind==='public'?'public':'room',id()+id(),1);}}
else if(action==='checkin'){let room=await one("SELECT * FROM rooms WHERE id=? AND hotel=? AND kind='room' AND active=1",b.room,b.hotel);if(!room)fail('Select an active room.');if(await one('SELECT id FROM stays WHERE room=? AND active=1 AND checkout>?',room.id,t))fail('This room has an active stay. Check it out first.');let checkout=new Date(b.checkout).getTime();if(!clean(b.name)||!Number.isFinite(checkout)||checkout<=t)fail('Enter guest name and a future checkout.');let sid=id(),pin=String(crypto.getRandomValues(new Uint32Array(1))[0]%900000+100000);await database().batch([database().prepare('UPDATE stays SET active=0 WHERE room=? AND active=1 AND checkout<=?').bind(room.id,t),database().prepare('INSERT INTO stays VALUES (?,?,?,?,?,?,?,?)').bind(sid,b.hotel,room.id,clean(b.name,100),await hash(sid+pin),t,checkout,1)]);return Response.json({pin,id:sid});}
else if(action==='checkout'){let stay=await one('SELECT * FROM stays WHERE id=? AND hotel=? AND active=1',b.id,b.hotel);if(!stay)fail('Stay not found.');if(await one("SELECT id FROM requests WHERE stay=? AND status NOT IN ('Completed','Cancelled','Rejected')",stay.id))fail('Complete or cancel the open requests before checkout.');await database().batch([database().prepare('UPDATE stays SET active=0 WHERE id=?').bind(stay.id),database().prepare('DELETE FROM guest_sessions WHERE stay=?').bind(stay.id)]);}
else if(action==='resetPin'){let stay=await one('SELECT * FROM stays WHERE id=? AND hotel=? AND active=1',b.id,b.hotel);if(!stay)fail('Stay not found.');let pin=String(crypto.getRandomValues(new Uint32Array(1))[0]%900000+100000);await database().batch([database().prepare('UPDATE stays SET pin=? WHERE id=?').bind(await hash(stay.id+pin),stay.id),database().prepare('DELETE FROM guest_sessions WHERE stay=?').bind(stay.id)]);await log(b.hotel,'admin',m.name,'audit','Room access code rotated');return Response.json({pin});}
else if(action==='extend'){let checkout=new Date(b.checkout).getTime();if(!Number.isFinite(checkout)||checkout<=t)fail('Choose a future checkout.');await run('UPDATE stays SET checkout=? WHERE id=? AND hotel=? AND active=1',checkout,b.id,b.hotel);}
else if(action==='member'){let email=clean(b.email,150).toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||!clean(b.name))fail('Enter a name and valid email.');let role=['admin','head','staff'].includes(b.role)?b.role:'staff';if(b.id){let old=await one('SELECT * FROM members WHERE id=? AND hotel=?',b.id,b.hotel);if(!old)fail('Staff member not found.');let hotel=await one('SELECT owner FROM hotels WHERE id=?',b.hotel);if(old.user===hotel.owner&&(role!=='admin'||b.active===false))fail('The hotel owner must remain an administrator.');if(old.email!==email)fail('Create a new account to change the staff email.');await run('UPDATE members SET name=?,role=?,department=?,active=? WHERE id=?',clean(b.name,100),role,clean(b.department,80)||'Reception',b.active===false?0:1,b.id);}else{if(await one('SELECT id FROM members WHERE hotel=? AND email=?',b.hotel,email))fail('This email already has an account.');let mid=id(),code=loginCode();await run('INSERT INTO members (id,hotel,email,user,name,role,department,active,invite,invite_until) VALUES (?,?,?,?,?,?,?,?,?,?)',mid,b.hotel,email,null,clean(b.name,100),role,clean(b.department,80)||'Reception',1,await hash(mid+code.replace('-','')),t+INVITE_MS);extra.code=code;}}
else if(action==='invite'){let old=await one('SELECT * FROM members WHERE id=? AND hotel=? AND active=1',b.id,b.hotel);if(!old)fail('Staff member not found.');let code=loginCode();await run('UPDATE members SET invite=?,invite_until=? WHERE id=?',await hash(old.id+code.replace('-','')),t+INVITE_MS,old.id);extra.code=code;}
else if(action==='service'){let c=b.config||{};if(!clean(b.name))fail('Enter a service name.');const modes=['Free','Fixed price','Per item','Per person','Per hour','Per trip','Package','Quote required'];if(!modes.includes(c.mode))fail('Select a price type.');let conf={description:clean(c.description,2000),image:safeurl(c.image),mode:c.mode,price:Math.round(Number(c.price)*100)||0,fee:Math.round(Number(c.fee)*100)||0,tax:Number(c.tax)||0,available:c.available!==false,open:clean(c.open,5),close:clean(c.close,5),minutes:Math.max(1,Math.min(Number(c.minutes)||30,10080)),maxQty:Math.max(1,Math.min(Number(c.maxQty)||20,100)),terms:clean(c.terms,1500),variants:(Array.isArray(c.variants)?c.variants:[]).slice(0,30).map((v:any)=>({name:clean(v.name,100),price:Math.round(Number(v.price)*100)}))};if(!Number.isSafeInteger(conf.price)||!Number.isSafeInteger(conf.fee)||conf.price<0||conf.fee<0||conf.tax<0||conf.tax>100||conf.variants.some((v:any)=>!v.name||!Number.isFinite(v.price)||v.price<0))fail('Check prices and taxes.');let vals=[clean(b.name,100),clean(b.category,100),clean(b.department,80),'room',['published','paused','draft','archived'].includes(b.status)?b.status:'draft',JSON.stringify(conf)];if(b.id){await run('UPDATE services SET name=?,category=?,department=?,audience=?,status=?,config=? WHERE id=? AND hotel=?',...vals,b.id,b.hotel);}else await run('INSERT INTO services VALUES (?,?,?,?,?,?,?,?)',id(),b.hotel,...vals);}
else if(action==='place'){if(!clean(b.name))fail('Enter a recommendation name.');let c=b.config||{};let conf={description:clean(c.description,1500),budget:clean(c.budget,100),bestTime:clean(c.bestTime,100),address:clean(c.address,300),maps:safeurl(c.maps),website:safeurl(c.website),image:safeurl(c.image),sponsored:!!c.sponsored,reviewed:new Date().toISOString().slice(0,10)};let vals=[clean(b.name,100),clean(b.category,100),JSON.stringify(conf),b.active===false?0:1];if(b.id)await run('UPDATE places SET name=?,category=?,config=?,active=? WHERE id=? AND hotel=?',...vals,b.id,b.hotel);else await run('INSERT INTO places VALUES (?,?,?,?,?,?)',id(),b.hotel,...vals);}
else fail('Unknown action.');await log(b.hotel,'admin',m.name,'audit',action+' '+clean(b.name||b.label||b.id));return Response.json({ok:true,...extra});
}catch(e:any){console.error('desk-write',e.message);return Response.json({error:e.status?e.message:'Could not save. Please retry.'},{status:e.status||503});}}
